use Test::Simple 'tests' : 6

use Graph::Enhanced

g = Graph(directed=False, multiedged=True)
buf = split(/\n/, <<'EOF')
% Generated by graph_tools (version 0.1) at Wed Dec 21 12:31:55 2005
% undirected, 4 vertices, 3 edges
4 3 1
2 1
1 1 3 1
2 1 4 1
3 1
EOF
g.import_graph('metis', buf)
ok(len(g.vertices()) == 4)
ok(len(g.edges()) == 3)
ok(g.has_edge(1, 2))
ok(g.has_edge(2, 3))
ok(g.has_edge(3, 4))
ok(g.get_edge_weight_by_id(3, 4, 0) eq '1')
